#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'build-essential'
cookbook 'yum'
cookbook 'nodejs'
cookbook 'nginx', git: 'https://github.com/opscode-cookbooks/nginx'